from __future__ import annotations

from typing import Protocol, Iterable

from codecollector.domain.models import RelationRecord, SymbolRecord


class IndexStore(Protocol):
    def get_known_files(self, project_root: str) -> dict[str, str]: ...
    def replace_file_contents(
        self,
        project_root: str,
        file_path: str,
        file_hash: str,
        module_name: str,
        symbols: Iterable[SymbolRecord],
        relations: Iterable[RelationRecord],
    ) -> None: ...
    def replace_knowledge_relations(self, project_root: str, relations: Iterable[RelationRecord]) -> None: ...
    def replace_search_documents(self, project_root: str, documents: Iterable[dict[str, str]]) -> None: ...
    def list_search_documents(self, project_root: str) -> list[dict[str, str]]: ...
    def delete_file(self, project_root: str, file_path: str) -> None: ...
    def delete_project(self, project_root: str) -> dict[str, int]: ...
    def get_symbol(self, project_root: str, qualname: str) -> SymbolRecord | None: ...
    def list_symbols(self, project_root: str) -> list[SymbolRecord]: ...
    def list_symbols_in_file(self, project_root: str, file_path: str) -> list[SymbolRecord]: ...
    def list_symbols_by_short_name(self, project_root: str, short_name: str) -> list[SymbolRecord]: ...
    def list_outbound_relations(self, project_root: str, source_qualname: str) -> list[RelationRecord]: ...
    def list_inbound_relations_for_qualname(self, project_root: str, target_qualname: str) -> list[RelationRecord]: ...
    def list_inbound_relations_for_name(self, project_root: str, target_name: str) -> list[RelationRecord]: ...
    def list_relations_by_kind(self, project_root: str, relation_kind: str) -> list[RelationRecord]: ...
